trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  GRAPH_TOKEN: $(secretToken)
  CHEF_API_TOKEN: $(chefToken)
  GOOGLE_APPLICATION_CREDENTIALS: $(gcpCreds)

steps:
  - task: PowerShell@2
    displayName: 'Query Intune for Non-Compliant Devices'
    inputs:
      targetType: 'filePath'
      filePath: 'scripts/query-intune.ps1'

  - script: scripts/query-chef.sh
    displayName: 'Get Chef Node States'

  - script: scripts/trigger-chef-run.sh
    displayName: 'Trigger Chef Remediation if Last Run > 24h'

  - script: scripts/fetch-gcp-logs.sh
    displayName: 'Fetch Critical Logs from GCP Logging'
